[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]

markers = [
    "unit: marks unit tests (no external dependencies, fast)",
    "integration: Tests that hit the DB or run API endpoints",
    "migration: marks tests that check alembic migrations (deselect with '-m \"not migration\"')",
]
