"""empty message

Revision ID: 23981d6d5991
Revises: f2a3ebda8787
Create Date: 2025-10-02 07:55:46.769579

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "23981d6d5991"
down_revision: Union[str, Sequence[str], None] = "f2a3ebda8787"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
