"""empty message

Revision ID: 6d84e167a009
Revises: 761d06685c02
Create Date: 2025-10-02 08:37:15.700839

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6d84e167a009"
down_revision: Union[str, Sequence[str], None] = "761d06685c02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audit_events", "matched_rule_ids")
    op.drop_column("audit_events", "source")
    op.drop_column("audit_events", "ip_address")
    op.drop_column("audit_events", "request_id")
    op.drop_column("audit_events", "previous_value")
    op.drop_column("audit_events", "target_entity")
    op.drop_column("audit_events", "new_value")
    op.drop_column("audit_events", "decision_summary")
    op.drop_column("audit_events", "explanation")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audit_events",
        sa.Column("explanation", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "audit_events",
        sa.Column("decision_summary", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "audit_events",
        sa.Column(
            "new_value",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "audit_events",
        sa.Column("target_entity", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "audit_events",
        sa.Column(
            "previous_value",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "audit_events",
        sa.Column("request_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "audit_events",
        sa.Column("ip_address", postgresql.INET(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "audit_events",
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "audit_events",
        sa.Column(
            "matched_rule_ids",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
