version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "[%(asctime)s] [%(levelname)s] %(name)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  json:
    (): pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(levelname)s %(name)s %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
  console_json:
    class: logging.StreamHandler
    formatter: json
    stream: ext://sys.stdout

loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: no
  uvicorn.error:
    level: INFO
    handlers: [console]
    propagate: no
  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: no
  app:
    level: INFO
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console]
